name: Automation on Trivy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Docker and Run Trivy Scan
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          echo "Scanning started"
          docker run --rm -v ${{ github.workspace }}:/project aquasec/trivy fs --severity HIGH,CRITICAL,MEDIUM /project > trivy-scan-report.txt || true

      - name: Upload Trivy Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-report
          path: trivy-scan-report.txt
